name: 'Setup Platform'
description: 'Setup platform-specific dependencies (Java for Android, Node.js, Bun)'

inputs:
  platform:
    description: 'Platform to setup (android or ios)'
    required: true
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22'

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup Java for Android
      if: inputs.platform == 'android'
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

